### ISSUE TITLE
Choice of TX/RX pins; LD2450 firmware versions

### ISSUE THREAD

**Issue by dwildstr** [Chreece/LD2450-ESPHome#3]
GPIO21 and GPIO22 are not hardware UART pins on ESP32; is there a reason not to use one of the hardware UART pairs (1 and 3, or 16 and 17) for this component?

Also, firmware 1.2.23051810 is many builds behind current; how compatible is this code with the current stable or dev firmware?

**Comment by Chreece** [comment]
You can use any GPIO pins support UART, the code is an example...
I updated also the readme a bit, the yaml is compatible with the latest LD2450 firmware and all the feature releases since the protocol isn't likely to be changed.
As soon as HiLink releases a working android app so I can test the code, I will develope more features from the latest firmware
